#!/usr/bin/env bash
# Publish site/*.html as the `site` Edge Function (Storage serves HTML as text/plain, so the page is served by a function).
#   ./scripts/publish-site.sh
set -euo pipefail
cd "$(dirname "$0")/.."
python3 -I - <<'PY'
import json, glob, os
import re, html as H
pages = {os.path.basename(f)[:-5]: open(f, encoding='utf-8').read() for f in sorted(glob.glob('site/*.html'))}
def to_text(h):
    h = re.sub(r'<script.*?</script>|<style.*?</style>', '', h, flags=re.S)
    h = re.sub(r'</(h1|h2|h3|p|li|div|pre|tr)>', '\n\n', h); h = re.sub(r'<br\s*/?>', '\n', h)
    h = re.sub(r'<[^>]+>', '', h); h = H.unescape(h)
    return re.sub(r'\n{3,}', '\n\n', re.sub(r'[ \t]+', ' ', h)).strip() + '\n'
texts = {k: to_text(v) for k, v in pages.items()}
with open('supabase/functions/site/pages.js', 'w', encoding='utf-8') as out:
    out.write('// Generated by scripts/publish-site.sh from site/*.html. Do not edit by hand.\n')
    out.write('export const PAGES = ' + json.dumps(pages, ensure_ascii=False, indent=0) + ';\n')
    out.write('export const PAGES_TEXT = ' + json.dumps(texts, ensure_ascii=False, indent=0) + ';\n')
print('bundled pages:', ', '.join(pages))
PY
supabase functions deploy site --no-verify-jwt --use-api
echo "Live at https://ccvhvxbqtvqbhexhrjnj.supabase.co/functions/v1/site"
